config/routes.rb
Rails.application.routes.draw do
  filter :locale

  devise_for :admins, :controllers => {:sessions => "admins/devise/sessions" }
  devise_for :creators, :controllers => {:registrations=> "creators/devise/registrations", :sessions => "creators/devise/sessions"}
  devise_for :users, :controllers => {:sessions => "users/devise/sessions", :invitations => 'users/devise/invitations' }

  resources :admins, only: :show do
    resources :badges, :controller => "admins/badges"
    resources :creators, only: [:index, :destroy], :controller => "admins/creators"
    resources :users, only: [:index, :destroy], :controller => "admins/users"
    resources :games, only: [:index, :destroy], :controller => "admins/games"
  end
  resources :creators, only: [:show, :edit, :update] do
    resources :games, :controller => "creators/games", except: :index do
      resources :rules, :controller => "creators/rules", except: :show
    end
  end
  resources :users, only: [:show, :edit, :update] do
    resources :games, :controller => "users/games", only: :show
    resources :rules, :controller => "users/rules" do
      member do
        post 'mark_pending', as: :rule_pending
        post 'mark_complete', as: :rule_complete, :controller => "creators/rules"
      end
    end
  end

  get 'about'=> "home#about"
  root to: "home#index"

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  # Validations
  validates :name, presence: true
  # validates :achieved, inclusion: { in: [true, false], message: "%{value} is not a valid achievement flag." }

  # Upload
  mount_uploader :badge, AvatarUploader

  # Associations
  has_many :user_badges
  has_many :users, through: :user_badges
end

app/controllers/admins/badges_controller.rb
class Admins::BadgesController < AdminsController
  before_filter :authenticate_admin!
  before_action :set_badge, only: [:show, :edit, :update, :destroy]
  before_action :prepare_admin

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to admin_badge_path(@admin, @badge), notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to admin_badge_path(@admin, @badge), notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to admin_badges_path(@admin), notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    def prepare_admin
      @admin = current_admin if admin_signed_in?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params[:badge].permit(:name, :badge, :admin_id, :badge_type)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/Admins/badges/_form.html.haml
.container
  .col-md-8
    = form_for [@admin, @badge], html: {class: "form-horizontal"} do |f|
      - if @badge.errors.any?
        #error_explanation
          %h2= "#{pluralize(@badge.errors.count, "error")} prohibited this badge from being saved:"
          %ul
            - @badge.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.label :name, "Badge Name", class: "col-md-6 control-label"
        .col-sm-6
          = f.text_field :name, placeholder: "Enter badge name", class: "form-control"
      .form-group
        .col-sm-6
          = f.text_field :badge_type, placeholder: "Badge type", class: "form-control"
      .col-md-5
        .form-group
          .row
            = f.label "Upload your Avatar", class: "col-sm-5 control-label", style: "margin-top:-15px;"
          .row
            .col-md-6
              = image_tag "http://placehold.it/120x120/95a5a6/ffffff", class: "preview img-thumbnail" , style: "width:120px;height:120px"
          .row
            .col-md-4
              %span{class: "btn btn-primary btn-block btn-file", style: "margin-left:15px;margin-top:7px;"}
                Upload
                = f.file_field :badge, id: "imgfile"
      .form-group
        = f.submit 'Save Badge', class: "btn btn-success"
%footer
  :javascript
    $("#imgfile").change(function(){
        if (this.files && this.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('.preview').attr('src', e.target.result);
            }
            reader.readAsDataURL(this.files[0]);
        }
    });

app/views/Admins/badges/edit.html.haml
%h1 Editing badge

= render 'form'

= link_to 'Show', admin_badge_path(@admin, @badge)
\|
= link_to 'Back', admin_badges_path

app/views/Admins/badges/index.html.haml
.row
  %h2 All Badges
  = link_to 'Create New Badge', new_admin_badge_path(@admin), class: "btn btn-success btn-sm pull-right"
.row
  %table{class: "table table-hover table-condensed table-striped login-wrap"}
    - @badges.each do |badge|
      %tr
        %td
          = badge.name
        %td
          = badge.badge_type
        %td= link_to 'Show', admin_badge_path(@admin, badge)
        %td= link_to 'Edit', edit_admin_badge_path(@admin, badge)
        %td= link_to 'Destroy', admin_badge_path(@admin, badge), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/Admins/badges/new.html.haml
%h1 New badge

= render 'form'

= link_to 'Back', admin_badges_path(@admin)

app/views/Admins/badges/show.html.haml
%h3 Badge Details

%h4 #{@badge.name}
= image_tag @badge.badge.url
= link_to 'Edit', edit_admin_badge_path(@admin, @badge)
\|
= link_to 'Back', admin_badges_path(@admin)