config/routes.rb
Rails.application.routes.draw do
  filter :locale

  devise_for :admins, :controllers => {:sessions => "admins/devise/sessions" }
  devise_for :creators, :controllers => {:registrations=> "creators/devise/registrations", :sessions => "creators/devise/sessions"}
  devise_for :users, :controllers => {:sessions => "users/devise/sessions", :invitations => 'users/devise/invitations' }

  resources :admins, only: :show do
    resources :badges, :controller => "admins/badges"
    resources :creators, only: [:index, :destroy], :controller => "admins/creators"
    resources :users, only: [:index, :destroy], :controller => "admins/users"
    resources :games, only: [:index, :destroy], :controller => "admins/games"
  end
  resources :creators, only: [:show, :edit, :update] do
    resources :games, :controller => "creators/games", except: :index do
      resources :rules, :controller => "creators/rules", except: :show
    end
  end
  resources :users, only: [:show, :edit, :update] do
    resources :games, :controller => "users/games", only: :show
    resources :rules, :controller => "users/rules" do
      member do
        post 'mark_pending', as: :rule_pending
        post 'mark_complete', as: :rule_complete, :controller => "creators/rules"
      end
    end
  end

  get 'about'=> "home#about"
  root to: "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  # Devise
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Upload
  mount_uploader :avatar, AvatarUploader

  # Validations
  validates :name, :presence => true
  validates :pts, numericality: { only_integer: true, greater_than_or_equal_to: 0}

  # Associations
  belongs_to :game
  has_many :user_rules
  has_many :rules, through: :user_rules

  has_many :user_badges
  has_many :badges, through: :user_badges
  # Functions
  def update_points(new_points)
    self.update_attribute(:pts, new_points)
  end

  def reset_points
    self.update_attribute(:pts, 0)
  end

  def set_starter_rank
    self.update_attribute(:rank, self.game.starter_rank)
  end

  def check_rank
    if pts >= self.game.pts_per_rule * 4
      self.set_rank(self.game.expert_rank)
    elsif pts >= self.game.pts_per_rule * 2
      self.set_rank(self.game.normal_rank)
    elsif
      self.set_rank(self.game.starter_rank)
    end
  end

  def set_rank(rank)
    self.update_attribute(:rank, rank)
  end

  def award_badge
    self.first_sign_in
    self.early
    # self.lastmonth
    self.number_sign_ins
    # self.high_rules
    # self.normal_rules
    # self.low_rules
  end

  def first_sign_in
    user_badge_entry = UserBadge.find_or_create_by!(user_id: self.id, game_id: self.game.id, badge_id: Badge.find_by(badge_type: "firstsignin").id)
    user_badge_entry.update(achieved: true) if self.sign_in_count >= 1
  end

  def early
    user_badge_entry = UserBadge.find_or_create_by!(user_id: self.id, game_id: self.game.id, badge_id: Badge.find_by(badge_type: "early").id)
    if self.current_sign_in_at.strftime("%H").to_i >= 3 && self.current_sign_in_at.strftime("%H").to_i <= 7
      user_badge_entry.update(achieved: true)
    end
  end

  def lastmonth
    user_badge_entry = UserBadge.find_or_create_by!(user_id: self.id, game_id: self.game.id, badge_id: Badge.find_by(badge_type: "lastmonth").id)
    if self.current_sign_in_at <= 1.month.ago
      user_badge_entry.update(achieved: true)
    end
  end

  def number_sign_ins
    user_badge_entry = UserBadge.find_or_create_by!(user_id: self.id, game_id: self.game.id, badge_id: Badge.find_by(badge_type: "signinl1").id)
    user_badge_entry.update(achieved: true) if self.sign_in_count >= 10

    user_badge_entry = UserBadge.find_or_create_by!(user_id: self.id, game_id: self.game.id, badge_id: Badge.find_by(badge_type: "signinl2").id)
    user_badge_entry.update(achieved: true) if self.sign_in_count >= 20

    user_badge_entry = UserBadge.find_or_create_by!(user_id: self.id, game_id: self.game.id, badge_id: Badge.find_by(badge_type: "signinl3").id)
    user_badge_entry.update(achieved: true) if self.sign_in_count >= 70
  end

  def high_rules
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "highl1").id, achieved: true) if self.sign_in_count >= 10
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "highl2").id, achieved: true) if self.sign_in_count >= 20
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "highl3").id, achieved: true) if self.sign_in_count >= 30
  end

  def normal_rules
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "normall1").id, achieved: true) if self.sign_in_count >= 10
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "normall2").id, achieved: true) if self.sign_in_count >= 20
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "normall3").id, achieved: true) if self.sign_in_count >= 30
  end

  def low_rules
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "lowl1").id, achieved: true) if self.sign_in_count >= 10
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "lowl2").id, achieved: true) if self.sign_in_count >= 20
    @user_badge_entry.update(badge_id: Badge.find_by(badge_type: "lowl3").id, achieved: true) if self.sign_in_count >= 30
  end
    # if @user_badge_entry
    #   puts "Awarded Badge"
    # else
    #   puts "ERROR AWARD"
    # end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminsController
  before_filter :authenticate_admin!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :prepare_admin

  # GET /badges
  # GET /badges.json
  def index
    @users = User.all
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path(@admin), notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = user.find(params[:id])
    end

    def prepare_admin
      @admin = current_admin if admin_signed_in?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params[:user].permit(:name, :badge, :admin_id)
    end
end

app/controllers/users/games_controller.rb
class Users::GamesController < ApplicationController
  before_filter :authenticate_user!
  before_action :prepare_user
  before_action :set_game

  # GET /games/1
  # GET /games/1.json
  def show
    @rules = @game.rules
    @completed_rules = @game.rules.joins(:user_rules).where(user_rules: {user_id: @user.id, status: UserRule.statuses[:complete]}).order(:updated_at).all.to_a
    @top_users = @game.users.order(pts: :desc).take(3)
    @users = @game.users.where.not(id: @top_users).order(pts: :desc).where.not(name: "")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = @user.game
    end

    def prepare_user
      @user = current_user if current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params[:game].permit(:name, :description, :pts_per_rule, :expert_rank, :normal_rank, :starter_rank)
    end
end

app/controllers/users/rules_controller.rb
class Users::RulesController < ApplicationController
  def mark_pending
    @user = current_user
    @rule = Rule.find(params[:id])
    @user_rule_entry = UserRule.new(user_id: @user.id , rule_id: @rule.id, game_id: @rule.game.id)

    respond_to do |format|
      if @user_rule_entry.update_status(:pending)
        format.html { redirect_to @user, notice: "Rule #{@rule.description.truncate(40)} was marked as pending. Awaiting Creator to approve." }
        format.json { head :no_content }
      else
        format.html { redirect_to @user, notice: "Rule \"#{@rule.description.truncate(40)}\" was NOT marked as pending. Please try again." }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :prepare_user

  def show
    @game = @user.game
    @rules = @game.rules.joins('LEFT OUTER JOIN user_rules ON user_rules.rule_id = rule_id').order('user_rules.status DESC').distinct
    @pend_rules = UserRule.where(user_id: @user, status: UserRule.statuses[:pending]).all.count
    @comp_rules = UserRule.where(user_id: @user, status: UserRule.statuses[:complete]).all.count
    @position = @game.users.order(pts: :desc).all.to_a.index(@user) + 1
    @badges = Badge.joins('LEFT OUTER JOIN user_badges ON user_badges.user_id = user_id AND user_badges.game_id ='+ @game.id.to_s).distinct
    @user.award_badge
    @earned_badges = UserBadge.where(user_id: @user.id, game_id: @game.id, achieved: true).all.to_a.count
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(users_params)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def prepare_user
    @user = User.find(params[:id]) if params[:id]
  end

  def users_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def check_achieved(badge)
    user_badge_entry = UserBadge.where(user_id: @user.id, game_id: @game.id, badge_id: badge.id).take
    # debugger
    unless user_badge_entry.nil?
      if user_badge_entry.achieved?
        badge_class = ''
      else
        badge_class = 'badge-lock'
      end
    else
      badge_class = 'badge-lock'
    end
    return badge_class
  end

  def badge_name(badge)
    name = t('badge.firstsignin') if badge.badge_type == "firstsignin"
    name = t('badge.early') if badge.badge_type == "early"
    name = t('badge.lastmonth') if badge.badge_type == "lastmonth"
    name = t('badge.signinl1') if badge.badge_type == "signinl1"
    name = t('badge.signinl2') if badge.badge_type == "signinl2"
    name = t('badge.signinl3') if badge.badge_type == "signinl3"
    name = t('badge.highl1') if badge.badge_type == "highl1"
    name = t('badge.highl2') if badge.badge_type == "highl2"
    name = t('badge.highl3') if badge.badge_type == "highl3"
    name = t('badge.normall1') if badge.badge_type == "normall1"
    name = t('badge.normall2') if badge.badge_type == "normall2"
    name = t('badge.normall3') if badge.badge_type == "normall3"
    name = t('badge.lowl1') if badge.badge_type == "lowl1"
    name = t('badge.lowl2') if badge.badge_type == "lowl2"
    name = t('badge.lowl3') if badge.badge_type == "lowl3"
    name = t('badge.firstsocial') if badge.badge_type == "firstsocial"
    name = t('badge.sociall1') if badge.badge_type == "sociall1"
    name = t('badge.sociall2') if badge.badge_type == "sociall2"
    name = t('badge.sociall3') if badge.badge_type == "sociall3"
    return name
  end
end

app/views/users/edit.html.haml
.container
  %h3 #{t('views.user_profile.edit_profile')}
  .col-md-offset-2
    = form_for @user do |user|
      = user.error_messages class: 'alert alert-error'

      .col-md-6
        .form-group
          = user.label :name, t('views.user_profile.name'), class: "col-sm-6 control-label"
          = user.text_field :name, placeholder: "#{t('views.user_profile.name')}", class: "form-control"

        .form-group
          .row
            = user.label t('views.user_profile.upload_your_avatar'), class: "col-sm-5 control-label", style: "margin-top:-15px;"
          .row
            = image_tag @user.avatar.url, class: "preview img-thumbnail" , style: "width:150px;height:150px"
          .row
            .col-md-5
              %span{class: "btn btn-primary btn-block btn-file"}
                = t('views.user_profile.upload')
                = user.file_field :avatar, id: "imgfile"
        .form-group
          = user.submit t('views.user_profile.save_changes'), class: "btn btn-block btn-success"

%footer
  :javascript
    $("#imgfile").change(function(){
        if (this.files && this.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('.preview').attr('src', e.target.result);
            }
            reader.readAsDataURL(this.files[0]);
        }
    });

app/views/users/show.html.haml
.container
  .row.profile-info-user
    .col-md-offset-1
      .ribbon.ribbon-blue.ribbon-large.ribbon-div
        .banner
          .text
            =t('views.home.user')
      %div{style: "background-color: rgba(255, 255, 255);height:168px;"}
        .col-md-1
          = image_tag @user.avatar.url , class: "img-circle profile-image"
        .col-md-10
          .row{style: "padding-top:10px;"}
            .col-md-3
              %h2 #{@user.name}
            .col-md-5{style: "margin-top:20px;"}
              %span{class: "label label-default title-h4"}
                #{@user.rank}
            .col-md-4{style: "margin-top:20px;"}
              %span{class: "label label-success title-h4"}
                #{@user.pts} #{t('views.home.points', count: @user.pts)}
          .row
            .col-md-2
              %label{class: "game-list-title"} #{@earned_badges} #{t('views.home.badges', count: @earned_badges)}
            .col-md-3
              %label{class: "game-list-title"} #{@pend_rules} #{t('views.user_profile.pending_rules_count', count: @pend_rules)}
            .col-md-3
              %label{class: "game-list-title"} #{@comp_rules} #{t('views.user_profile.comp_rules_count', count: @comp_rules)}
            .col-md-4
              %label{class: "game-list-title"} #{t('views.home.leaderboard_position')}: #{@position.ordinalize}

  .row{style: "margin-top:10px;"}
    .col-md-5
      .row
        %label{class: "game-list-title"} #{@game.name}
        = link_to t('views.home.view_game'), user_game_path(@user, @game), class: "pull-right btn btn-info", style: "margin-top:5px;margin-right:65px;"
      .row
      .row
        %label{class:"game-list-title"} #{t('views.home.rules')}
      .row
        %div{id: "rules", style: "height:270px;"}
          %table{class: "table table-hover table-condensed table-striped"}
            - @rules.each do |rule|
              %tr
                %td
                  = rule.description
                %td
                  %span{class: "#{rule_priority(rule)}"}
                    #{rule_priority_text(rule)}
                %td
                  - unless check_status(@user, rule)
                    = form_for rule, :url => rule_pending_user_rule_path(@user, rule), :html => {:method => :post} do |f|
                      = f.button type: "submit", class: "mark" do
                        %i{class: "#{rule_status(@user,rule)}"}
                        #{rule_status_text(@user,rule)}
                  - else
                    %i{class: "#{rule_status(@user,rule)}", style: "#{rule_status_color}"}
                    %label{style: "#{rule_status_color}"} #{rule_status_text(@user,rule)}

    .col-md-6.col-md-offset-1
      .row
        %label{class: "game-list-title"} #{t('views.home.competition_badges')}
      .row{id: "rules", style: "height:385px;text-align:center;"}
        - @badges.each do |badge|
          .col-md-3{title: "#{badge_name(badge)}", data: {toggle: "tooltip", placement: "top"}}
            = image_tag badge.badge.url, class: "user-badge #{check_achieved(badge)}"