config/routes.rb
Rails.application.routes.draw do
  filter :locale

  devise_for :admins, :controllers => {:sessions => "admins/devise/sessions" }
  devise_for :creators, :controllers => {:registrations=> "creators/devise/registrations", :sessions => "creators/devise/sessions"}
  devise_for :users, :controllers => {:sessions => "users/devise/sessions", :invitations => 'users/devise/invitations' }

  resources :admins, only: :show do
    resources :badges, :controller => "admins/badges"
    resources :creators, only: [:index, :destroy], :controller => "admins/creators"
    resources :users, only: [:index, :destroy], :controller => "admins/users"
    resources :games, only: [:index, :destroy], :controller => "admins/games"
  end
  resources :creators, only: [:show, :edit, :update] do
    resources :games, :controller => "creators/games", except: :index do
      resources :rules, :controller => "creators/rules", except: :show
    end
  end
  resources :users, only: [:show, :edit, :update] do
    resources :games, :controller => "users/games", only: :show
    resources :rules, :controller => "users/rules" do
      member do
        post 'mark_pending', as: :rule_pending
        post 'mark_complete', as: :rule_complete, :controller => "creators/rules"
      end
    end
  end

  get 'about'=> "home#about"
  root to: "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  ##TODO layout
  def index
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def check_home
    if current_page?(root_path) || current_page?(about_path)
      body_class = ""
    else
      body_class ="margin-bottom:-80px;"
    end
    # body_class ="margin-bottom:-80px;"
    return body_class
  end
end

app/views/home/about.html.haml
-# = javascript_include_tag "http://vjs.zencdn.net/4.6/video.js"
-# = javascript_include_tag "vjs.youtube.js"
-# = javascript_include_tag "videojs.markers.js"
-# = stylesheet_link_tag "http://vjs.zencdn.net/4.6/video-js.css", rel: "stylesheet"
-# = stylesheet_link_tag "videojs.markers.css", rel: "stylesheet"
-# = stylesheet_link_tag "videojs-overlay.css", rel: "stylesheet"

-# :javascript
-#   videojs.options.flash.swf = "video-js.swf";
%h2 #{t('nav.about')}

-# %video#my-video.video-js.vjs-default-skin.vjs-big-play-centered{controls: "", "data-setup" => "{ \"techOrder\": [\"youtube\"], \"src\": \"https://www.youtube.com/watch?v=RoYvr-KXvLs\" }", height: "360", preload: "auto", src: "", width: "640"}

-# :javascript
-#   // var may_video = videojs('my-video');

-#   videojs('my-video').ready(function(){

-#     //load the marker plugin
-#     this.markers({
-#       setting: {
-#         //set style, markertip, and breakOverlay
-#         markerStyle: {
-#           'width':'8px',
-#           'background-color': 'orange'
-#         },
-#         markerTip:{
-#           display: true,
-#           default_text: "",
-#           show_colon: false
-#         },

-#         forceInitialization: true // doesn't wait for loadedmetadata event
-#       },
-#       marker_breaks:[60.5, 600, 750, 900],
-#       marker_text  :['Question 1','Question 2','Question 3','Question 4']
-#     });

-#   })

app/views/home/index.html.haml
.container
  .row
    .col-md-5.col-md-offset-5
      %h3 #{t('nav.gamify')}
    .col-md-5.col-md-offset-5
      %h4 #{t('views.login.slogan')}

  - unless user_signed_in? || creator_signed_in?
    .row
      .col-md-4.col-md-offset-1.login-wrap
        %label{class: "title-h5"} #{t('views.login.creator')}
        = form_for("creator", url: new_creator_session_path, html: {class: "form-horizontal"}) do |c|
          .form-group
            .col-xs-12
              = c.text_field :email, placeholder: t('views.home.email'), class: "form-control"
          .form-group
            .col-xs-12
              = c.password_field :password, autocomplete: "off", placeholder: t('views.home.password'), class: "form-control"
          .form-group
            .col-xs-12
              = c.submit t('views.login.signin'), class: "btn btn-warning btn-block"

        .col-md-6.btn-login
          = link_to t('views.login.signup'), new_creator_registration_path, class: "btn btn-primary btn-block"

      -# .col-md-2
      -#   = image_tag 'logo.png', class: "img-circle img-responsive", style:"width:170px;margin-top:50px;margin-left:-120px;"
      .col-md-4.col-md-offset-2.login-wrap
        %label{class: "title-h5"} #{t('views.home.user')}
        = form_for("user", url: new_user_session_path, html: {class: "form-horizontal"}) do |c|
          .form-group
            .col-xs-12
              = c.text_field :email, placeholder: t('views.home.email'), class: "form-control"
          .form-group
            .col-xs-12
              = c.password_field :password, autocomplete: "off", placeholder: t('views.home.password'), class: "form-control"
          .form-group
            .col-xs-12
              = c.submit t('views.login.signin'), class: "btn btn-info btn-block"

  - else
    .row
    %br
      .col-md-4.col-md-offset-4
        - if creator_signed_in?
          = link_to "Begin", creator_path(current_creator), class: "btn btn-block btn-primary"

        - else
          - if user_signed_in?
            = link_to "Begin", user_path(current_user), class: "btn btn-block btn-primary"